name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential software-properties-common curl git wget
        
    - name: Install global npm packages
      run: |
        npm install -g npm@11.2.0
        npm install -g rollup
        npm install -g rimraf
        
    - name: Build WebLLM Components
      run: |
        cd optlite-webllm/webllm-components
        export HUSKY=0
        export HUSKY_SKIP_HOOKS=1
        npm install --ignore-scripts
        npm install --save-dev rollup@2.56.2
        chmod +x cleanup-index-js.sh
        chmod +x node_modules/.bin/rollup
        export PATH="$PATH:$(npm bin)"
        npm run build || true
        
    - name: Build Python wheel
      run: |
        cd optlite-webllm/optlite-components
        pip install wheel
        python3 setup.py bdist_wheel -d dist

    - name: Build OPTLite Components
      run: |
        cd optlite-webllm/optlite-components
        npm install
        chmod +x node_modules/.bin/webpack
        npm run build:prod
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Copy WebLLM components to build directory
      run: |
        # Copy WebLLM components to the build directory
        cp -r optlite-webllm/webllm-components/lib/* optlite-webllm/optlite-components/build/webllm/
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: optlite-webllm/optlite-components/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 